### ISSUE TITLE
Request: Chrome/ium version to use in Kiwi, Edge, Lemur Android browsers

### ISSUE THREAD

**Issue by BD9Max** [M-Reimer/cookiewhitelist#2]
This addon is so good it does what it's supposed to: clear cookies except whitelist, it does it well and doesn't have anything extra hogging around.

History and cache cleaners are different.

We need this addon for Chromium based browsers too: Kiwi, Lemur, Edge, Yandex... I reckon soon Opera, Vivaldi, Brave etc.

**Comment by M-Reimer** [comment]
No, sorry. I won't develop anything for a browser I don't use.
